<?php
/**
 * Aegis Web Installer
 *
 * Security note: Always secure this installer (delete after use).
 */

session_start();

$step = isset($_GET["step"]) ? intval($_GET["step"]) : 1;

function renderHeader($title = "Web Installer")
{
    echo "<!DOCTYPE html><html><head><title>" .
        htmlspecialchars($title) .
        "</title>";
    echo "<style>body{font-family:sans-serif;margin:40px;}input,select{padding:5px;margin:5px;} .error{color:red;}</style>";
    echo "</head><body><h1>" . htmlspecialchars($title) . "</h1>";
}

function renderFooter()
{
    echo "</body></html>";
}

if ($step === 1) {
    renderHeader("Step 1: GitHub Repository"); ?>
    <form method="post" action="?step=2">
        <label>GitHub Repository URL:<br>
            <input type="text" name="repo_url" placeholder="https://github.com/username/repo.git" required>
        </label><br>
        <label>Branch (default: main):<br>
            <input type="text" name="branch" value="main">
        </label><br>
        <button type="submit">Next</button>
    </form>
    <?php renderFooter();
} elseif ($step === 2 && $_SERVER["REQUEST_METHOD"] === "POST") {

    $_SESSION["repo_url"] = trim($_POST["repo_url"]);
    $_SESSION["branch"] = trim($_POST["branch"]) ?: "main";

    renderHeader("Step 2: Database Setup");

    $error = null;
    if (isset($_POST["db_host"])) {
        $host = trim($_POST["db_host"]);
        $name = trim($_POST["db_name"]);
        $user = trim($_POST["db_user"]);
        $pass = $_POST["db_pass"];

        try {
            $dsn = "mysql:host={$host};dbname={$name};charset=utf8mb4";
            $pdo = new PDO($dsn, $user, $pass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);
            $_SESSION["db"] = [
                "host" => $host,
                "name" => $name,
                "user" => $user,
                "pass" => $pass,
            ];
            header("Location: ?step=3");
            exit();
        } catch (Exception $e) {
            $error =
                "Database connection failed: " .
                htmlspecialchars($e->getMessage());
        }
    }
    ?>
    <?php if ($error): ?><p class="error"><?= $error ?></p><?php endif; ?>
    <form method="post" action="?step=2">
        <label>Database Host:<br>
            <input type="text" name="db_host" value="<?= htmlspecialchars(
                $_POST["db_host"] ?? "localhost"
            ) ?>" required>
        </label><br>
        <label>Database Name:<br>
            <input type="text" name="db_name" value="<?= htmlspecialchars(
                $_POST["db_name"] ?? ""
            ) ?>" required>
        </label><br>
        <label>Database User:<br>
            <input type="text" name="db_user" value="<?= htmlspecialchars(
                $_POST["db_user"] ?? ""
            ) ?>" required>
        </label><br>
        <label>Database Password:<br>
            <input type="password" name="db_pass" value="<?= htmlspecialchars(
                $_POST["db_pass"] ?? ""
            ) ?>" required>
        </label><br>
        <button type="submit">Test & Continue</button>
    </form>
    <?php renderFooter();
} elseif ($step === 3) {

    if (!isset($_SESSION["db"])) {
        header("Location: ?step=2");
        exit();
    }

    renderHeader("Step 3: SSH Key Setup");
    ?>
    <p>To deploy from GitHub over SSH, you need an SSH key:</p>
    <ol>
        <li>On your server, run: <code>ssh-keygen -t rsa -b 4096 -C "your_email@example.com"</code></li>
        <li>Copy the contents of <code>~/.ssh/id_rsa.pub</code> into your GitHub account under <b>Settings → SSH and GPG keys</b>.</li>
        <li>Ensure <code>ssh-agent</code> is running and your key is added with <code>ssh-add ~/.ssh/id_rsa</code>.</li>
    </ol>
    <form method="post" action="?step=4">
        <label>Have you added your SSH key to GitHub?
            <select name="ssh_ready">
                <option value="yes">Yes</option>
                <option value="no">No (skip for now)</option>
            </select>
        </label><br>
        <button type="submit">Next</button>
    </form>
    <?php renderFooter();
} elseif ($step === 4 && $_SERVER["REQUEST_METHOD"] === "POST") {

    renderHeader("Final Step: Configuration Complete");

    $config = <<<PHP
<?php
/**
 * Aegis Configuration
 *
 * Auto-generated by installer on: {date("Y-m-d H:i:s")}
 * IMPORTANT: Do not commit this file to version control!
 */
return [
    'repo_url' => '{$_SESSION["repo_url"]}',
    'branch'   => '{$_SESSION["branch"]}',
    'database' => [
        'host' => '{$_SESSION["db"]["host"]}',
        'name' => '{$_SESSION["db"]["name"]}',
        'user' => '{$_SESSION["db"]["user"]}',
        'pass' => '{$_SESSION["db"]["pass"]}',
    ],
];
PHP;

    file_put_contents(__DIR__ . "/config.php", $config);
    ?>
    <p>✅ Configuration file created at <code>config.php</code>.</p>
    <p>Next steps:</p>
    <ol>
        <li>Clone the repo manually:<br>
            <code>git clone -b <?= htmlspecialchars(
                $_SESSION["branch"]
            ) ?> <?= htmlspecialchars($_SESSION["repo_url"]) ?></code>
        </li>
        <li>Run your database migrations/import SQL schema.</li>
        <li>Delete this <code>index.php</code> installer file for security.</li>
    </ol>
    <?php renderFooter();
} else {
    header("Location: ?step=1");
    exit();
}
